### ISSUE TITLE
Peer dependency 

### ISSUE THREAD

**Issue by mario-imperato** [georgebyte/rxjs-observable-store#18]
I was installing using 13.0.2 angular stuff. When installing the store I found a peer dependency. 
Is it correct to force?
Thank you. Below the output.
Mario

npm install rxjs-observable-store --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: app-console-sites@0.0.0
npm ERR! Found: rxjs@7.4.0
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~7.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"6.x" from rxjs-observable-store@3.0.4
npm ERR! node_modules/rxjs-observable-store
npm ERR!   rxjs-observable-store@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by johnmarian** [comment]
+1
I don't see any conflicts in this library with Angular 7, so it should just be a matter of updating the package and rebuilding.

**Comment by johnmarian** [comment]
> I was installing using 13.0.2 angular stuff. When installing the store I found a peer dependency. Is it correct to force? Thank you. Below the output. Mario
> 
> npm install rxjs-observable-store --save npm ERR! code ERESOLVE npm ERR! ERESOLVE unable to resolve dependency tree npm ERR! npm ERR! While resolving: app-console-sites@0.0.0 npm ERR! Found: rxjs@7.4.0 npm ERR! node_modules/rxjs npm ERR! rxjs@"~7.4.0" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer rxjs@"6.x" from rxjs-observable-store@3.0.4 npm ERR! node_modules/rxjs-observable-store npm ERR! rxjs-observable-store@"*" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Using `--force` with npm will get you past this for now

**Comment by JoelMacKenzie** [comment]
I'm using Angular 13 as well and installed with `--force`, but as soon as I add an `import` to my `app.module.ts` I'm no longer able to build.  The build starts, but never finishes and no errors are displayed.

Any idea what would cause that?

**Comment by georgebyte** [comment]
I've published the [v3.1.0](https://github.com/georgebyte/rxjs-observable-store/releases/tag/v3.1.0) release of `rxjs-observable-store` which should take care of both issues reported here.
