### ISSUE TITLE
Patch state using an array as argument

### ISSUE THREAD

**Issue by ZandorZ** [georgebyte/rxjs-observable-store#9]
First of all, congrats for doing this library. I use it a lot :)

Is it possible to use an array instead of writing the complete path when patching the state ?

Something like this ..

```
const myPath = ['user', 'age'];
store.patchState(30, ...myPath);

```
I'm using a deep nested state object and the path needs to be dynamic

Thanks in advance

**Comment by FFKL** [comment]
@ZandorZ  Hello! You can use path like this
```typescript
const myPath = ['user', 'age'] as const;
store.patchState(30, ...myPath);
```
